# Generated by Django 4.1 on 2022-12-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('usuarioCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioCompra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUC', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('DNI_representante', models.CharField(max_length=8)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unidad_medida', models.CharField(choices=[('U', 'Unidades'), ('Kg', 'Kilogramos'), ('L', 'Litros')], default='U', max_length=20)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComprasApp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField(default=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComprasApp.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComprasApp.insumo')),
            ],
        ),
    ]
