# Generated by Django 4.1 on 2022-12-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ComprasApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tipoCliente', models.CharField(choices=[('Natural', 'Natural'), ('Jurídico', 'Jurídico')], max_length=10)),
                ('tipoDocumento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('Carné de Extranjería', 'Carné de Extranjería')], max_length=25)),
                ('nroDocumento', models.CharField(max_length=11, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('enUso', models.BooleanField(default=False)),
                ('horaUltimoUso', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('liberar_mesa', 'Liberar mesa'),),
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('Plato', 'Plato'), ('Bebida', 'Bebida'), ('Acompañamiento', 'Acompañamiento'), ('Otros', 'Otros')], default='Plato', max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPedido', models.CharField(choices=[('Salon', 'Salon'), ('Delivery', 'Delivery')], default='Salon', max_length=20)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(blank=True, max_length=45)),
                ('pagado', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.cliente')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.mesa')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioRegistra', to=settings.AUTH_USER_MODEL)),
                ('usuarioReparte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioReparte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_entregar_pedido', 'Entregar pedido'),),
            },
        ),
        migrations.CreateModel(
            name='DetallePlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComprasApp.insumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.plato')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('indicaciones', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.plato')),
            ],
        ),
    ]
