# Generated by Django 4.1 on 2022-12-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PedidosApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoApertura', models.BooleanField(default=True)),
                ('importeInicial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('importeFinal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaCierre', models.DateTimeField(null=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta al contado', 'Tarjeta al contado'), ('Tarjeta en cuotas', 'Tarjeta en cuotas')], max_length=20)),
                ('tipoComprobante', models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importeTotal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField(default=True)),
                ('igv', models.DecimalField(decimal_places=2, default=0.18, max_digits=3)),
                ('apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CajaApp.aperturacaja')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidosApp.pedido')),
            ],
        ),
    ]
